### PR TITLE
Feature/user lang

### PR DESCRIPTION
**Pull request by briri**
## Description

Part of work for #128 

- Added `Language` model, resolver with `languages` query and supporting GraphQL types
- Added `languageId` to `User` and `Template` (we will want to add to DMPs too down the road)
- Added a `cleanup()` function to the `Template` model that gets called on `create` or `update`
- Updated the `cleanup()` function on the `Template` and `User` models so that it only allows the `languageId` to be one of the supported languages

I opted to leave the languages as a hard-coded list for now in the Model. I don't see a scenario where we would need them to be table based. Adding a new language will likely require dev work to add translation files etc. for the foreseeable future. We can reevaluate later on if we come up with a workflow that we could offer to allow admins to add new languages via the UI.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Include any relevant details for your test configuration.

- Updated unit tests
- Verified that languages were being returned in the Apollo server explorer interface

**Note that you need to run `bash data-migrations/process.sh` to add the `languageId` column to the `users` and `templates` tables and seed the existing records. You DO NOT need to nuke the existing DB!**

## Checklist:
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I updated the CHANGELOG.md and added documentation if necessary
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jupiter007** [comment]
@briri could you also add the ability to update the User table? There are currently no resolvers that handle updating the user table with any Profile data edits.

**Comment by briri** [comment]
> @briri could you also add the ability to update the User table? There are currently no resolvers that handle updating the user table with any Profile data edits.

Yes, I wanted to break it up into separate PRs to make it more manageable. This is part one

**Comment by jupiter007** [comment]
> > @briri could you also add the ability to update the User table? There are currently no resolvers that handle updating the user table with any Profile data edits.
> 
> Yes, I wanted to break it up into separate PRs to make it more manageable. This is part one

Ah ok. Thanks. Is there a separate ticket for that? Just wondering if I need to update the ticket description here: https://github.com/CDLUC3/dmsp_backend_prototype/issues/128 or if you'll be opening both PRs under this ticket.

**Review by jupiter007 — APPROVED** [review]

**Comment by briri** [comment]
was going to just have 2 PRs for the one ticket

**Pull request merged**
