### PR TITLE
Chore/remove oauth

### LINKED ISSUE #92: Remove oauth-server package
The `oauth-server` package has a critical security vulnerability due to its reliance on an outdated version of `lodash`

We can remove the package and reimplement at a future date with a newer package.

### PR DESCRIPTION
**Pull request by briri**
## Description

Removed `oauth-server` package and all related code. The package has not been updated in 3 years and had a dependency on a version of `lodash` that had a critical security vulnerability.

Fixes #92

## Type of change
Please delete options that are not relevant

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Removed the package and code and then ran unit tests.

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I updated the CHANGELOG.md and added documentation if necessary
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by jupiter007** [comment]
@briri did you mean to create the PR against the "main" branch? Just checking.

**Comment by briri** [comment]
oops. no. I just changed it to development.

**Comment by briri** [comment]
@jupiter007 I just updated the change log and rebase this PR against the development branch

**Review by jupiter007 — APPROVED** [review]

**Comment by jupiter007** [comment]
> @jupiter007 I just updated the change log and rebase this PR against the development branch

Thanks Brian. LGTM.

**Comment by briri** [comment]
thanks @jupiter007 make sure to pull in the latest from the development branch into your branch for the section resolvers/models

**Comment by jupiter007** [comment]
> thanks @jupiter007 make sure to pull in the latest from the development branch into your branch for the section resolvers/models

Thanks @briri for the reminder. I updated my "feature/add-section-model-and-resolver" branch with the latest updates from "development". I responded to all of your comments on that branch. Please take a look when you have time.

**Pull request merged**
